name: CI

on: [push]

jobs:
  swift-bionic-job:
    container: 
      image: swift:5.1.2-bionic
    
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]
        
    steps:
    - uses: actions/checkout@master
    - name: Run unit tests
      run: |
        apt-get -qq update && apt-get install -y \
          libssl-dev zlib1g-dev \
          && rm -r /var/lib/apt/lists/*
        swift test
    - name: Build library in release mode
      run: |
        apt-get -qq update && apt-get install -y \
          libssl-dev zlib1g-dev \
          && rm -r /var/lib/apt/lists/*
        swift build -c release
